#!/bin/bash

# This app_profile will be sourced prior to execution of PyRunner job.
# NOTE: Only variables with "APP_" prefix will be available during job.
#       All other variables will be discarded.

export APP_VERSION=0.0.1

export APP_NAME="timing-bot-runner"
export APP_ROOT_DIR="$(cd $(dirname ${BASH_SOURCE})/..; pwd)"
export APP_CONFIG_DIR="${APP_ROOT_DIR}/config"
export APP_TEMP_DIR="${APP_ROOT_DIR}/temp"
export APP_ROOT_LOG_DIR="${APP_ROOT_DIR}/logs"
export APP_LOG_RETENTION="30"
export APP_WORKER_DIR="${APP_ROOT_DIR}/workers"

DATE=$(date +"%Y-%m-%d")
export APP_EXEC_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

export APP_LOG_DIR="${APP_ROOT_LOG_DIR}/${DATE}"

if [ ! -e ${APP_LOG_DIR}  ]; then mkdir -p ${APP_LOG_DIR}; fi
if [ ! -e ${APP_TEMP_DIR} ]; then mkdir -p ${APP_TEMP_DIR}; fi
